// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiLangDemo.Data;

#nullable disable

namespace MultiLangDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517061055_SeedLocalizationData")]
    partial class SeedLocalizationData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiLangDemo.Models.LocalizationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalizationResources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en",
                            Key = "Welcome",
                            Value = "Welcome to Database Localization"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en",
                            Key = "Description",
                            Value = "Dynamic translations loaded from database."
                        },
                        new
                        {
                            Id = 3,
                            Culture = "hi",
                            Key = "Welcome",
                            Value = "डेटाबेस लोकलाइजेशन में आपका स्वागत है"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "hi",
                            Key = "Description",
                            Value = "डेटाबेस से डायनामिक ट्रांसलेशन लोड किए गए हैं।"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
